spring:
  profiles:
    active: local # 기본 환경 선택
  application:
    name: DemoEngineController

---
spring:
  profiles: local
  server:
    port: 7001
    servlet:
      context-path: /mdp/Enginecontrol/v1/face
    
