server:
    port: 27000

spring:
    application:
        name: micro-service-1

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:38080/eureka/
    instance:
        prefer-ip-address: true
        leaseRenewalIntervalInSeconds: 10
        #instanceId: ${spring.application.instance_id:${random.value}}
        #instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}