spring:
    application:
        name: discovery-service
#    boot:
#        admin:
#            url: http://localhost:8762


server:
    port: 38080

# -- Eureka
eureka:
    instance:
        hostname: 127.0.0.1
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
        register-with-eureka: false
        fetch-registry: false
    server:
        enable-self-preservation: false #자가보존모드(client 상태를 받을 수 없는 경우에도 일정기간 동안 레지스트리 유지) 설정
        #wait-time-in-ms-when-sync-empty: 0



