spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: FacePostExecutorSim
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: compute3:9300

server:
  port: 7006
  servlet:
    context-path: /mdp/Enginecontrol/v1/face


management:
  health:
    elasticsearch:
      enabled: false

config:
  saveIndexName: myindex
  facerawindexName: mdp_my_raw_face
  facemergeindexName: mdp_my_merge_face
  musicindexName: mdp_my_raw_music
  musicmergeindexName: mdp_my_merge_music